# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-25 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corelab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSamplePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[(0, 'Unknown'), (1, 'Inquery')], default='0', max_length=3, verbose_name='Event type')),
                ('instrument_time', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Instrument time at')),
                ('dateofcreation', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instrumentsamplepositions_instrument', to='corelab.Instruments', verbose_name='Instrument')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insttrumentsamplepositions_sample', to='corelab.OrderSamples', verbose_name='Order Sample')),
            ],
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(help_text='Date format: YYYY-MM-DD', verbose_name='Date of birth'),
        ),
    ]
