# Generated by Django 5.0.6 on 2025-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corelab", "0004_results_type_alter_results_order_qualitycontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tests",
            name="ext_code",
            field=models.CharField(
                max_length=30, null=True, verbose_name="External code"
            ),
        ),
    ]
